FROM node:lts-alpine AS builder
WORKDIR /build
COPY package*.json ./
RUN npm ci
COPY . .
RUN NITRO_PRESET=bun npm run build

FROM oven/bun:1-alpine
WORKDIR /app
COPY --from=builder /build/.output ./.output
EXPOSE 3000/tcp
ENTRYPOINT ["bun", "run", ".output/server/index.mjs"]
