name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci --prefer-offline --no-audit
      - run: npm run build:deno
      - uses: denoland/deployctl@v1
        with:
          project: "tapw"
          entrypoint: "main.js"
          root: "dist"
